# .github/workflows/swarm.yml
name: Super Swarm

on:
  schedule:
    - cron: "*/15 * * * *"  # Aktif setiap 15 menit
  workflow_dispatch:  # Boleh dijalankan manual

jobs:
  scrape_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Scraper
        run: |
          python swarm/core.py
